include:
  # 1: include the component
  - component: gitlab.com/to-be-continuous/python/gitlab-ci-python@6.6.1
    # 2: set/override component inputs
    inputs:
      image: registry.hub.docker.com/library/python:3
      pylint-enabled: true
      pylint-args: --ignore=tests
      pytest-enabled: true
