name: Build & Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
        exclude:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest
            python-version: '3.11'
    steps:
      - uses: actions/checkout@v4 # Checking out the repo
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Display Python version
        run: |
          python --version
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Lint with flake8
        run: |
          pip install flake8
          # Python syntax errors or undefined names
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true
      - name: Run pytest
        run: |
          pip install pytest
          python -m pytest --rootdir='tests' -v -s
