name: Build & Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        exclude:
          - os: macos-latest
          - os: windows-latest
            python-version: '2.7'
          - os: ubuntu-latest
            python-version: '2.7'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Display Python version
        run: python --version
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
      - name: Run pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest --rootdir='tests' main.py
