name: Build & Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']
        exclude:
          - os: macos-latest
          - os: windows-latest
          - os: ubuntu-latest
            python-version: '3.11'
    steps:
      - uses: actions/checkout@v4 # Checking out the repo
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'
      - name: Display Python version
        run: |
          python --version
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --max-line-length 1000 src/
        continue-on-error: true
      - name: Run pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest --rootdir='tests' -v -s
